### ISSUE TITLE
Мини-мод, исправляющий часть проблем со шрифтами

### ISSUE THREAD

**Issue by VitalyChashin** [ikarasik/terra-invicta-ru#7]
Добрый день. Вы не хотели бы использовать в локализации мод, исправляющий часть проблем со шрифтами, в частности, названия модулей хаба и отображение процентов успеха миссий на карте? Ссылка: https://github.com/VitalyChashin/TerraInvictaFontFix , ставится с Unity Mod Manager.

**Comment by ikarasik** [comment]
Я бы конечно хотел, но боюсь люди не осилят установку ещё дополнительных модов для шрифтов :\

**Comment by VitalyChashin** [comment]
Я попробую сделать какой-то простой инсталлятор, без UMM.
