### ISSUE TITLE
Евгений, проблема с лоадом зип

### ISSUE THREAD

**Issue by EvgeniiKuchma** [ikarasik/terra-invicta-ru#9]
день добрый, пытаюсь скачать зип , выдает инфу про отсутствие сертификата и не безопасное содержимое файла не подскажите в чем может быть проблема?

**Comment by ikarasik** [comment]
Добрый день, скорее всего если скачиваешь с яндекс браузера будут такие проблемы, попробуй гугл хром или файрфокс, должно помочь.

**Comment by EvgeniiKuchma** [comment]
Ок, спасибо 
--
Отправлено из Mail.ru для Android понедельник, 02 января 2023г., 19:28 +05:00 от Karasik  ***@***.*** :

**Comment by EvgeniiKuchma** [comment]
Извините за столь бесцеремонное письмо, но нашему Славке стало еще хуже.
https://telegra.ph/Eremeev-Slavik-09-01
Это ребенок моей двоюродной сестрёнки, если что.
 
 
--
r w
Отправлено из Почты  Mail.ru
https://telegra.ph/Eremeev-Slavik-09-01
